import React from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import * as z from "zod";
import { Permasalahan, Tamu } from "../types";
import { 
  FileText, 
  User, 
  Tag, 
  AlertCircle, 
  UserCheck, 
  Clock, 
  HelpCircle, 
  Calendar, 
  Link2,
  Sparkles,
  FileCheck
} from "lucide-react";

export const LIST_KATEGORI_MASALAH = [
  "Teknologi Informasi & Sistem Aplikasi",
  "Kurikulum & Pendampingan Peningkatan Mutu",
  "Perencanaan & Akuntabilitas Keuangan",
  "Kepegawaian & Umum"
];

export const LIST_PRIORITAS = ["Tinggi", "Sedang", "Rendah"] as const;

export const LIST_STATUS = [
  "Baru",
  "Diverifikasi",
  "Diproses",
  "Ditindaklanjuti",
  "Terkendali",
  "Belum Terkendali",
  "Ditutup"
] as const;

export const LIST_PIC = [
  "Drs. La Ode Ruslan, M.Si",
  "Fadlillah Ahmad, S.Kom",
  "Suwardi, S.T., M.T.",
  "Drs. Umar Faruq",
  "Erna S., S.i.P.",
  "Aulia Rahman, S.Kom."
];

const permasalahanSchema = z.object({
  idKasus: z.string().optional(),
  idTamu: z.string().min(1, { message: "ID Tamu wajib dihubungkan atau pilih Non-Tamu" }),
  tanggal: z.string().min(1, { message: "Tanggal wajib diisi" }),
  kategori: z.string().min(1, { message: "Kategori wajib dipilih" }),
  subKategori: z.string().min(2, { message: "Sub kategori minimal 2 karakter" }),
  permasalahan: z.string().min(10, { message: "Deskripsi permasalahan minimal 10 karakter" }),
  prioritas: z.enum(["Tinggi", "Sedang", "Rendah"]),
  pic: z.string().min(2, { message: "PIC Penanggungjawab wajib diisi" }),
  status: z.enum(["Baru", "Diverifikasi", "Diproses", "Ditindaklanjuti", "Terkendali", "Belum Terkendali", "Ditutup"]),
  
  // Optional Solution elements generated by AI & editable
  analisis: z.string().optional(),
  penyebab: z.string().optional(),
  solusiBpmp: z.string().optional(),
  tindakLanjut: z.string().optional(),
  tanggalTindakLanjut: z.string().optional()
});

type PermasalahanFormValues = z.infer<typeof permasalahanSchema>;

interface PermasalahanFormProps {
  initialValues?: Partial<Permasalahan>;
  initialSolusi?: any;
  tamuList: Tamu[];
  onSubmit: (values: PermasalahanFormValues) => void;
  onCancel: () => void;
  isSubmitting?: boolean;
}

const PermasalahanForm: React.FC<PermasalahanFormProps> = ({
  initialValues,
  initialSolusi,
  tamuList = [],
  onSubmit,
  onCancel,
  isSubmitting = false
}) => {
  const [isAnalyzing, setIsAnalyzing] = React.useState(false);
  const [aiError, setAiError] = React.useState<string | null>(null);

  const defaultValues: PermasalahanFormValues = {
    idKasus: initialValues?.idKasus || "",
    idTamu: initialValues?.idTamu || "-",
    tanggal: initialValues?.tanggal || new Date().toISOString().split("T")[0],
    kategori: initialValues?.kategori || LIST_KATEGORI_MASALAH[0],
    subKategori: initialValues?.subKategori || "",
    permasalahan: initialValues?.permasalahan || "",
    prioritas: initialValues?.prioritas || "Sedang",
    pic: initialValues?.pic || LIST_PIC[0],
    status: initialValues?.status || "Baru",
    analisis: initialSolusi?.analisis || "",
    penyebab: initialSolusi?.penyebab || "",
    solusiBpmp: initialSolusi?.solusiBpmp || "",
    tindakLanjut: initialSolusi?.tindakLanjut || "",
    tanggalTindakLanjut: initialSolusi?.tanggalTindakLanjut || new Date().toISOString().split("T")[0]
  };

  const {
    register,
    handleSubmit,
    setValue,
    getValues,
    formState: { errors }
  } = useForm<PermasalahanFormValues>({
    resolver: zodResolver(permasalahanSchema),
    defaultValues
  });

  const handleAnalyzeWithAi = async () => {
    const desc = getValues("permasalahan");
    if (!desc || desc.trim().length < 10) {
      alert("Tolong isi uraian masalah lengkap minimal 10 karakter sebelum melakukan analisis AI.");
      return;
    }

    setIsAnalyzing(true);
    setAiError(null);

    try {
      const response = await fetch("/api/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ permasalahan: desc })
      });

      if (!response.ok) {
        throw new Error("Gagal terhubung dengan layanan asisten AI.");
      }

      const result = await response.json();
      if (result && result.data) {
        const { kategori, prioritas, analisis, penyebab, solusiBpmp, tindakLanjut } = result.data;

        // Set Form Values
        if (kategori) {
          let mappedKat = kategori;
          if (kategori.includes("Teknologi") || kategori.includes("Sistem") || kategori.includes("Aplikasi")) {
            mappedKat = "Teknologi Informasi & Sistem Aplikasi";
          } else if (kategori.includes("Kurikulum") || kategori.includes("Mutu") || kategori.includes("Pendidikan")) {
            mappedKat = "Kurikulum & Pendampingan Peningkatan Mutu";
          } else if (kategori.includes("Perencanaan") || kategori.includes("Keuangan") || kategori.includes("Anggaran") || kategori.includes("Akuntabilitas")) {
            mappedKat = "Perencanaan & Akuntabilitas Keuangan";
          } else if (kategori.includes("Kepegawaian") || kategori.includes("Umum")) {
            mappedKat = "Kepegawaian & Umum";
          }
          setValue("kategori", mappedKat);
        }

        if (prioritas) {
          let mappedPrio = "Sedang";
          if (prioritas.toLowerCase().includes("tinggi")) mappedPrio = "Tinggi";
          else if (prioritas.toLowerCase().includes("rendah")) mappedPrio = "Rendah";
          setValue("prioritas", mappedPrio as "Tinggi" | "Sedang" | "Rendah");
        }

        if (analisis) setValue("analisis", analisis);
        if (penyebab) setValue("penyebab", penyebab);
        if (solusiBpmp) setValue("solusiBpmp", solusiBpmp);
        if (tindakLanjut) setValue("tindakLanjut", tindakLanjut);

        // Set standard target date to 30 days out
        const targetDate = new Date();
        targetDate.setDate(targetDate.getDate() + 30);
        setValue("tanggalTindakLanjut", targetDate.toISOString().split("T")[0]);

        // Auto-generate subCategory based on desc if empty
        const currentSub = getValues("subKategori");
        if (!currentSub || currentSub.trim() === "") {
          const words = desc.trim().split(/\s+/);
          const firstThreeWords = words.slice(0, 3).map(w => w.replace(/[^a-zA-Z0-9]/g, "")).join(" ");
          setValue("subKategori", "AI: " + (firstThreeWords || "Asistensi"));
        }
      } else {
        throw new Error("Layanan AI mengembalikan respons tidak valid.");
      }
    } catch (err: any) {
      console.error(err);
      setAiError(err.message || "Gagal melakukan analisis AI.");
      alert("Error AI: " + (err.message || "Terjadi kesalahan. Silakan isi form solusi secara manual."));
    } finally {
      setIsAnalyzing(false);
    }
  };

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-4 text-xs font-sans">
      <div className="bg-slate-50/50 p-4 rounded-xl border border-slate-100 grid grid-cols-1 md:grid-cols-2 gap-4">
        
        {/* Tanggal */}
        <div className="space-y-1">
          <label className="font-bold text-slate-700 flex items-center gap-1.5 uppercase tracking-wider text-[10px]">
            <Calendar className="w-3.5 h-3.5 text-bpmp-blue" /> Tanggal Pengaduan*
          </label>
          <input
            type="date"
            {...register("tanggal")}
            className={`w-full bg-white p-2.5 rounded-lg border text-xs focus:outline-none focus:ring-1 ${
              errors.tanggal ? "border-red-500 focus:ring-red-300" : "border-slate-200 focus:border-bpmp-blue focus:ring-bpmp-sky"
            }`}
          />
          {errors.tanggal && (
            <p className="text-red-500 text-[10px] mt-0.5">{errors.tanggal.message}</p>
          )}
        </div>

        {/* Hubungan ke ID Tamu */}
        <div className="space-y-1">
          <label className="font-bold text-slate-700 flex items-center gap-1.5 uppercase tracking-wider text-[10px]">
            <Link2 className="w-3.5 h-3.5 text-bpmp-blue" /> Hubungkan Ke Tamu / Kunjungan*
          </label>
          <select
            {...register("idTamu")}
            className={`w-full bg-white p-2.5 rounded-lg border text-xs focus:outline-none focus:ring-1 ${
              errors.idTamu ? "border-red-500 focus:ring-red-300" : "border-slate-200 focus:border-bpmp-blue"
            }`}
          >
            <option value="-">Non-Tamu (Asisten AI atau Pengaduan Langsung)</option>
            {tamuList.map((tamu) => (
              <option key={tamu.idTamu} value={tamu.idTamu}>
                {tamu.idTamu} - {tamu.nama} ({tamu.instansi})
              </option>
            ))}
          </select>
          {errors.idTamu && (
            <p className="text-red-500 text-[10px] mt-0.5">{errors.idTamu.message}</p>
          )}
        </div>

        {/* Kategori Permasalahan */}
        <div className="space-y-1">
          <label className="font-bold text-slate-700 flex items-center gap-1.5 uppercase tracking-wider text-[10px]">
            <Tag className="w-3.5 h-3.5 text-bpmp-blue" /> Kategori Permasalahan*
          </label>
          <select
            {...register("kategori")}
            className={`w-full bg-white p-2.5 rounded-lg border text-xs focus:outline-none focus:ring-1 ${
              errors.kategori ? "border-red-500 focus:ring-red-300" : "border-slate-200 focus:border-bpmp-blue"
            }`}
          >
            {LIST_KATEGORI_MASALAH.map((kat) => (
              <option key={kat} value={kat}>{kat}</option>
            ))}
          </select>
          {errors.kategori && (
            <p className="text-red-500 text-[10px] mt-0.5">{errors.kategori.message}</p>
          )}
        </div>

        {/* Sub Kategori */}
        <div className="space-y-1">
          <label className="font-bold text-slate-700 flex items-center gap-1.5 uppercase tracking-wider text-[10px]">
            <HelpCircle className="w-3.5 h-3.5 text-bpmp-blue" /> Sub-Kategori / Topik Khusus*
          </label>
          <input
            type="text"
            placeholder="Contoh: Sinkronisasi ARKAS BOSP, Masalah Dapodik"
            {...register("subKategori")}
            className={`w-full bg-white p-2.5 rounded-lg border text-xs focus:outline-none focus:ring-1 ${
              errors.subKategori ? "border-red-500" : "border-slate-200 focus:border-bpmp-blue focus:ring-bpmp-sky"
            }`}
          />
          {errors.subKategori && (
            <p className="text-red-500 text-[10px] mt-0.5">{errors.subKategori.message}</p>
          )}
        </div>

        {/* Uraian Permasalahan */}
        <div className="space-y-1 md:col-span-2">
          <div className="flex justify-between items-center mb-1">
            <label className="font-bold text-slate-700 flex items-center gap-1.5 uppercase tracking-wider text-[10px]">
              <FileText className="w-3.5 h-3.5 text-bpmp-blue" /> Uraian Masalah Lengkap*
            </label>
            <button
              type="button"
              onClick={handleAnalyzeWithAi}
              disabled={isAnalyzing}
              className="bg-purple-100 hover:bg-purple-200 text-purple-800 border border-purple-300 font-extrabold px-3 py-1.5 rounded-xl flex items-center gap-1.5 transition-all text-[10px] cursor-pointer disabled:opacity-50"
            >
              {isAnalyzing ? (
                <>
                  <div className="w-3 h-3 border-2 border-purple-800 border-t-transparent rounded-full animate-spin"></div>
                  Menganalisis...
                </>
              ) : (
                <>
                  <Sparkles className="w-3.5 h-3.5 text-purple-700 shrink-0" /> Analisis dengan AI
                </>
              )}
            </button>
          </div>
          <textarea
            rows={4}
            placeholder="Tuliskan keluhan atau laporan rincian hambatan operasional pendidikan di sini..."
            {...register("permasalahan")}
            className={`w-full bg-white p-2.5 rounded-lg border text-xs focus:outline-none focus:ring-1 ${
              errors.permasalahan ? "border-red-500 focus:ring-red-300" : "border-slate-200 focus:border-bpmp-blue focus:ring-bpmp-sky"
            }`}
          />
          {errors.permasalahan && (
            <p className="text-red-500 text-[10px] mt-0.5">{errors.permasalahan.message}</p>
          )}
          {aiError && (
            <p className="text-red-500 text-[10px] mt-0.5 font-bold">Error AI: {aiError}</p>
          )}
        </div>

        {/* Prioritas */}
        <div className="space-y-1 col-span-1">
          <label className="font-bold text-slate-700 flex items-center gap-1.5 uppercase tracking-wider text-[10px]">
            <AlertCircle className="w-3.5 h-3.5 text-bpmp-blue" /> Prioritas Kasus*
          </label>
          <select
            {...register("prioritas")}
            className={`w-full bg-white p-2.5 rounded-lg border text-xs focus:outline-none ${
              errors.prioritas ? "border-red-500" : "border-slate-200 focus:border-bpmp-blue"
            }`}
          >
            {LIST_PRIORITAS.map((prio) => (
              <option key={prio} value={prio}>{prio}</option>
            ))}
          </select>
          {errors.prioritas && (
            <p className="text-red-500 text-[10px] mt-0.5">{errors.prioritas.message}</p>
          )}
        </div>

        {/* PIC Penanggung Jawab */}
        <div className="space-y-1">
          <label className="font-bold text-slate-700 flex items-center gap-1.5 uppercase tracking-wider text-[10px]">
            <UserCheck className="w-3.5 h-3.5 text-bpmp-blue" /> PIC / Officer Ahli Penanggungjawab*
          </label>
          <select
            {...register("pic")}
            className={`w-full bg-white p-2.5 rounded-lg border text-xs focus:outline-none ${
              errors.pic ? "border-red-500" : "border-slate-200 focus:border-bpmp-blue"
            }`}
          >
            {LIST_PIC.map((person) => (
              <option key={person} value={person}>{person}</option>
            ))}
          </select>
          {errors.pic && (
            <p className="text-red-500 text-[10px] mt-0.5">{errors.pic.message}</p>
          )}
        </div>

        {/* Status Perkembangan */}
        <div className="space-y-1 md:col-span-2">
          <label className="font-bold text-slate-700 flex items-center gap-1.5 uppercase tracking-wider text-[10px]">
            <Clock className="w-3.5 h-3.5 text-bpmp-blue" /> Alur Status Kasus*
          </label>
          <select
            {...register("status")}
            className={`w-full bg-white p-2.5 rounded-lg border text-xs focus:outline-none ${
              errors.status ? "border-red-500" : "border-slate-200 focus:border-bpmp-blue"
            }`}
          >
            {LIST_STATUS.map((st) => (
              <option key={st} value={st}>{st}</option>
            ))}
          </select>
          {errors.status && (
            <p className="text-red-500 text-[10px] mt-0.5">{errors.status.message}</p>
          )}
        </div>

      </div>

      {/* AI Analysis and Recommendation Fields (Dapat Diedit Sesuai Kebutuhan) */}
      <div className="bg-purple-50/30 p-4 rounded-xl border border-purple-200/50 space-y-4">
        <h4 className="text-purple-900 font-extrabold text-[11px] uppercase tracking-wider flex items-center gap-2 font-display">
          <Sparkles className="w-4 h-4 text-purple-700 animate-pulse" /> Kajian Solusi & Rekomendasi (Dapat Diisi Manual / Otomatis AI)
        </h4>
        <p className="text-slate-500 text-[10px] -mt-2 leading-relaxed">
          Formulasi draf analisis, penyebab, rekomendasi solusi, dan tindak lanjut ini akan terintegrasi langsung dengan katalog draf solusi BPMP. Klik tombol &ldquo;Analisis dengan AI&rdquo; di atas untuk mengisi draf ini secara pintar.
        </p>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {/* Analisis */}
          <div className="space-y-1">
            <label className="font-bold text-slate-700 flex items-center gap-1.5 uppercase tracking-wider text-[9px]">
              <FileCheck className="w-3.5 h-3.5 text-purple-600 shrink-0" /> Analisis Gejala Masalah
            </label>
            <textarea
              rows={3}
              placeholder="Analisis teknis / administratif terhadap laporan hambat pengaduan..."
              {...register("analisis")}
              className="w-full bg-white p-2.5 rounded-lg border border-slate-200 focus:outline-none focus:border-purple-500 focus:ring-1 focus:ring-purple-200 text-xs"
            />
          </div>

          {/* Penyebab */}
          <div className="space-y-1">
            <label className="font-bold text-slate-700 flex items-center gap-1.5 uppercase tracking-wider text-[9px]">
              <AlertCircle className="w-3.5 h-3.5 text-purple-600 shrink-0" /> Akar Penyebab Utama
            </label>
            <textarea
              rows={3}
              placeholder="Akar penyebab utama (root cause) dari masalah ini..."
              {...register("penyebab")}
              className="w-full bg-white p-2.5 rounded-lg border border-slate-200 focus:outline-none focus:border-purple-500 focus:ring-1 focus:ring-purple-200 text-xs"
            />
          </div>

          {/* Solusi BPMP */}
          <div className="space-y-1 md:col-span-2">
            <label className="font-bold text-slate-700 flex items-center gap-1.5 uppercase tracking-wider text-[9px]">
              <Sparkles className="w-3.5 h-3.5 text-purple-600 shrink-0" /> Formulasi Rekomendasi Solusi BPMP
            </label>
            <textarea
              rows={3}
              placeholder="Langkah strategis / intervensi pembinaan teknis BPMP Maluku Utara untuk solusi masalah..."
              {...register("solusiBpmp")}
              className="w-full bg-white p-2.5 rounded-lg border border-slate-200 focus:outline-none focus:border-purple-500 focus:ring-1 focus:ring-purple-200 text-xs"
            />
          </div>

          {/* Tindak Lanjut */}
          <div className="space-y-1">
            <label className="font-bold text-slate-700 flex items-center gap-1.5 uppercase tracking-wider text-[9px]">
              <Clock className="w-3.5 h-3.5 text-purple-600 shrink-0" /> Tindak Lanjut Unit Kerja / Sekolah
            </label>
            <input
              type="text"
              placeholder="Contoh: Mengunggah PDF bukti fisik / mengikuti bimbtek susulan"
              {...register("tindakLanjut")}
              className="w-full bg-white p-2.5 rounded-lg border border-slate-200 focus:outline-none focus:border-purple-500 focus:ring-1 focus:ring-purple-200 text-xs"
            />
          </div>

          {/* Tanggal Tindak Lanjut */}
          <div className="space-y-1">
            <label className="font-bold text-slate-700 flex items-center gap-1.5 uppercase tracking-wider text-[9px]">
              <Calendar className="w-3.5 h-3.5 text-purple-600 shrink-0" /> Target Batas Tindak Lanjut
            </label>
            <input
              type="date"
              {...register("tanggalTindakLanjut")}
              className="w-full bg-white p-2.5 rounded-lg border border-slate-200 focus:outline-none focus:border-purple-500 focus:ring-1 focus:ring-purple-200 text-xs"
            />
          </div>
        </div>
      </div>

      <div className="flex justify-end gap-2 pt-4 border-t border-slate-100">
        <button
          type="button"
          onClick={onCancel}
          disabled={isSubmitting}
          className="bg-slate-100 hover:bg-slate-200 text-slate-600 font-bold px-4 py-2.5 rounded-xl text-xs transition-colors cursor-pointer"
        >
          Batal
        </button>
        <button
          type="submit"
          disabled={isSubmitting}
          className="bg-bpmp-blue hover:bg-bpmp-light-blue text-white font-extrabold px-6 py-2.5 rounded-xl text-xs transition-all shadow cursor-pointer disabled:opacity-50 font-display"
        >
          {isSubmitting ? "Menyimpan..." : (initialValues?.idKasus ? "Simpan Perubahan & Kajian" : "Eskalasi Kasus & Kajian AI")}
        </button>
      </div>
    </form>
  );
};

export default PermasalahanForm;
